name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy 
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        if: runner.os == 'Linux' && runner.tool_cache.dockerversion != '20.10'
        run: |
          sudo apt-get update
          sudo apt-get install docker.io -y

      - name: Log Docker version
        run: docker --version

      - name: Execute multiple commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/Laravel8-php7.4
            git pull origin main
