name: CI/CD

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy 
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} -i ${{ secrets.KEY }} 'cd /var/www/html/Laravel8-php7.4 && git pull origin main'
